version: '3'

services:
    app:
        image: silarhi/php-apache:7.4
        container_name: lab_esi_app
        volumes:
            - ./php:/app:ro
        restart: always
        networks:
            - internal
            - web

    varnish:
        image: varnish:6.3
        command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-t" , "0"]
        container_name: labvarnish_app
        volumes:
            - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.labs-esi.rule=Host(`labs.silarhi.fr`) && PathPrefix(`/esi`)"
            - "traefik.http.routers.labs-esi.entrypoints=websecure"
            - "traefik.http.routers.labs-esi.middlewares=labs-esi"
            - "traefik.http.middlewares.labs-esi.stripprefix.prefixes=/esi"
        restart: always
        networks:
            - internal
            - web

networks:
    internal:
        driver: bridge
    web:
        external: true
