version: '3'

services:
    app:
        image: silarhi/symfony-docker-ci:latest
        container_name: lab_ci_app
        env_file:
            - app.env
        environment:
            - APP_MAINTENANCE
        volumes:
            - /app/var/logs
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.labs-ci.rule=Host(`labs.silarhi.fr`)"
            - "traefik.http.routers.labs-ci.entrypoints=websecure"
        restart: always
        networks:
            - web

networks:
    web:
        external: true
